export enum ErrorCodes {
  USER_HAS_NOT_PERMISSION = 100,
  USER_NOT_FOUND = 101,
  USER_HAS_NOT_OWNER_PERMISSION = 102,
  INCORRECT_OTP = 103,

  INCORRECT_PASSWORD = 104,
  INCORRECT_LOGIN = 105, 

  EMAIL_ALREADY_REGISTERED = 603,
  PHONE_ALREADY_REGISTERED = 604,

  CATEGORY_NOT_FOUND = 601,

  COMPANY_NOT_FOUND = 501,

  PRODUCT_NOT_FOUND = 301,
  PRODUCT_COUNT_LIMITED = 302,

  NOTIFICATION_NOT_FOUND = 701,

  ORDER_ALREADY_DELIVERED = 802,

  PAYMENT_TYPE_NOT_ALLOWED = 850,
}
