export enum ErrorCodes {
  USER_HAS_NOT_PERMISSION = 100,
  USER_NOT_FOUND = 101,
  USER_HAS_NOT_OWNER_PERMISSION = 102,
  INCORRECT_OTP = 103,
  ONLY_SUPER_USER_ALLOWED = 104,

  INCORRECT_PASSWORD = 104,
  INCORRECT_LOGIN = 105, 

  EMAIL_ALREADY_REGISTERED = 603,
  PHONE_ALREADY_REGISTERED = 604,

  CATEGORY_NOT_FOUND = 601,

  COMPANY_NOT_FOUND = 501,

  PRODUCT_NOT_FOUND = 301,
  PRODUCT_COUNT_LIMITED = 302,

  NOTIFICATION_NOT_FOUND = 701,

  ORDER_ALREADY_DELIVERED = 802,

  PAYMENT_TYPE_NOT_ALLOWED = 850,
  PAYMENT_PRICE_EXCEED = 855,
}


export enum ErrorMessages {
  USER_HAS_NOT_PERMISSION = 'USER_HAS_NOT_PERMISSION',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_HAS_NOT_OWNER_PERMISSION = 'USER_HAS_NOT_OWNER_PERMISSION',
  INCORRECT_OTP = 'INCORRECT_OTP',
  ONLY_SUPER_USER_ALLOWED = 'ONLY_SUPER_USER_ALLOWED',

  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  INCORRECT_LOGIN = 'INCORRECT_LOGIN',

  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  PHONE_ALREADY_REGISTERED = 'PHONE_ALREADY_REGISTERED',

  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',

  COMPANY_NOT_FOUND = 'COMPANY_NOT_FOUND',

  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_COUNT_LIMITED = 'PRODUCT_COUNT_LIMITED',

  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',

  ORDER_ALREADY_DELIVERED = 'ORDER_ALREADY_DELIVERED',

  PAYMENT_TYPE_NOT_ALLOWED = 'PAYMENT_TYPE_NOT_ALLOWED',
  PAYMENT_PRICE_EXCEED = 'PAYMENT_PRICE_EXCEED',
}
