name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install PM2
        run: npm install pm2 -g

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test

      - name: Build and deploy (replace with your deployment script)
        run: |
          npm run build
          pm2 start ./dist/main.js --name horeca
        env:
          NODE_ENV: production
