name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # - name: Run tests
      #   run: npm test

      - name: Build and deploy (replace with your deployment script)
        run: |
          npm run build

      - name: Run DEV server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd Projects/horeca
            git pull
            npm install
            pm2 restart horeca
